#!/bin/sh

#convert xc:none -page A5 blank.pdf

OUTF=`basename "$1" .epub`.pdf
# font-size: 9 to 11pt
ebook-convert "$1" "$OUTF" --paper-size a5 --pdf-default-font-size 12 --pdf-page-margin-top 56.7 --pdf-page-margin-bottom 56.7 --pdf-page-margin-right 60.95 --pdf-page-margin-left 60.95 # --pdf-odd-even-offset 9.92
# --pdf-page-margin-bottom 76.5 --pdf-page-numbers 
#--pdf-add-toc
# --pdf-page-number-map "if (n < 10) 0; else n-10;"
