#!/bin/sh
# a simple wrapper around bib2bib that removes any personal annotations
which bib2bib || { echo "Error: requires bib2bib (from the bibtex2html package)"; exit 1; }

bib2bib --no-comment \
  --remove annote \
  --remove mendeley-tags \
  --remove keywords \
  --remove comment \
  --remove owner \
  --remove timestamp \
  --remove review \
  --remove file \
  "$@"
#  --remove abstract \
