#!/bin/sh
# required packages: mp3cd (which requires normalize-audio, sox,..) and cdrdao
TMP="/tmp"

# mp3cd's default /dev/cdrecorder is not present on my machine and changing
# the target device in the $HOME/.cdrdao file alone isn't enough because mp3cd
# itself
DEV="/dev/sr0"
if [ -f "$TMP/cdda.toc" ]; then
  echo "Found disk table-of-contents, commencing burning.."
  # TODO check length of playlist and size of cd
  # cdrdao disk-info -v 0 | grep "CD-R empty           : yes"
  # need root for write access (?)
  echo "$@"
  mp3cd --no-cd-text -t "$TMP" -d "$DEV" --stage toc_ok -c "--overburn $@"
#ERROR: It seems that driver selected by cdrdao for /dev/sr0 does not support CD-TEXT writing. Either disable CD-TEXT via '--no-cd-text' or select a different driver (e.g. try using '--driver generic-mmc-raw')
else
  if [ $# -ne 1 ]; then
    echo "Usage: burnm3u <playlist.m3u>"
    exit 1
  fi
  mp3cd -t "$TMP" -d "$DEV" --skip cdr_ok,burn "$1"
  if [ $? -eq 0 ]; then
    echo "All audio files normalised and ready for burning, have a look at $TMP/cdda.toc to check"
    echo "the audio tags for correctness, then run burnm3u again to burn the"
    echo "normalised files to disk. This second call to burnm3u requires no arguments,"
    echo "any arguments will be passed on to cdrdao to control the burning process."
    echo
    echo "It is recommended that you check the available drive speeds by calling"
    echo "$ wodim -prcap"
    echo "and then passing a suitably low speed to burnm3u, e.g."
    echo "$ burnm3u --speed 8"
    cdrdao disk-info -v 0 | grep "CD-R empty           : yes"
    if [ $? -ne 0 ]; then
      echo "Also don't forget to put in a blank cd!"
    fi
  fi
fi
