#!/bin/sh

# render a file from markdown (with citeproc [@References]) to github markdown.
# pandoc will look for a template file 'jekyll.markdown_github' in its template
# path - use this template to control how much of the YAML header is rendered.
# this template, for example, will only produce a minimal header in the output:
#---
#title: $title$
#$if(description)$
#description: $description$
#$endif$
#---
#$body$

if [ $# -ne 1 ]; then
  echo "Usage: pandoc-jekyll-references <filename>"
  exit 1
fi

pandoc --bibliography=$HOME/library.bib --metadata=link-citations:True --from=markdown --to=markdown-citations-header_attributes --wrap=preserve --template=jekyll -o "$1.md" "$1" &&
# --template=jekyll
# +yaml_metadata_block
# postprocessing to:
# 1. make reference-links target="_self" (kramdown-specific)
# 2. remove Mendeley's overly zealous tilde and underscore protection
# FIXME also take pre-underscore backslash?
sed -i -e 's/\(#ref-\w\+)\)/\1{:target="_self"}/g' -e 's/{\([^~_]*\)\([~_]\)}/\1\2/g' "$1.md"
# 3. make quotations italics (match is greedy until final parentheses on line)
# -e 's/^> /> "*\1*"/g'
