#!/bin/sh
if [ $# -ne 1 ]; then
  echo "Usage: pandoc-latex <input-file>"; exit 1
fi
OUTF="`basename $1 .md`.pdf"
pandoc -t latex -V papersize:"a4paper" -V geometry:"margin=1in" --number-sections "$1" --bibliography=$HOME/library.bib -o "$OUTF"
xdg-open "$OUTF" 2> /dev/null
